apiVersion: apps/v1
kind: Deployment
metadata:
  name: testweb-deployment
  labels:
    app: testweb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testweb
  template:
    metadata:
      labels:
        app: testweb
    spec:
      containers:
      - name: testweb
        image: devopsyogi/kube:v1.0.0
        ports:
        - containerPort: 80
